site_name: balcony
repo_url: https://github.com/oguzhan-yilmaz/balcony
repo_name: oguzhan-yilmaz/balcony

nav:
    - Home: index.md
    - Installation & QuickStart: quickstart.md
    - Cookbook: cookbook.md
    - Feature Gallery: feature-gifs.md
    - 'Run on Docker': docker.md
    - 'As a Python library': as-a-python-library.md
    - 'balcony terraform-import': 
      - 'About Import Configurations': about-terraform-import.md
      - 'Generating Terraform Import Blocks': terraform-import.md
      - 'Actually Generate TF code with Docker': terraform-import-docker.md
      - 'Terraform Import Configuration Wizard': terraform-import-wizard.md
    - 'Config Env Vars': environment-variables.md
    - 'How it Works?': 
      - 'About boto3': how-it-works/about-boto3.md
      - 'About balcony': how-it-works/about-balcony.md
    - Development:
      - development/developing-custom-resource-nodes.md
      - development/about-relations.md
      - development/yaml-resource-nodes.md
      - development/custom-resource-nodes.md
      - 'Diagram: Reading Operations': development/diagram-of-reading-operations.md
    - Reference:
      - 'ResourceNode': reference/resource-node.md
      - 'YamlResourceNode': reference/yaml-resource-node.md
      - 'ServiceNode': reference/service-node.md
      - 'ServiceReader': reference/service-reader.md
      - reference/relations.md
      - reference/registries.md
      - reference/aws.md
      - reference/yaml_configuration.md
      - 'Utilities': 
        - reference/utils.md
        - reference/botocore_utils.md
    - 'Star History': misc.md
theme:
  name: material
  language: en
  font:
    text: Roboto
  features:
    - navigation.tracking
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

  palette: 
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep orange
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep orange
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oguzhan-yilmaz
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/oguzhan-y/
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/oguzhan_y_

      
      
markdown_extensions:
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html

plugins:
- search
- mkdocstrings
- autorefs